name: check git tag
on:
  workflow_call:
    inputs:
      version-history-file:
        description: バージョン情報が記載されたファイルへのパス
        type: string
        required: true
      github-sha:
        description: GitHub SHA
        type: string
        required: true
      github-pull-request-html-url:
        description: GitHub Pull Request HTML URL
        type: string
        required: true
    secrets:
      github-token:
        description: GitHubトークン
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  check_git_tag:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: extract version
        id: version
        run: |
          LOG_FILE=git_log
          
          NEWTAG=$(grep -E "v[0-9].[0-9].[0-9]" ${{ inputs.version-history-file }} | sed -r 's/^.*(v[0-9].[0-9].[0-9]).*$/\1/' | sort -r | head -1)
          echo -e "NEW_TAG=${NEWTAG}" | tee ${LOG_FILE}

          PRETAG=$(git tag | sort -r | head -1)
          
          if [ -z ${PRETAG}]; then
            echo -e "No PRETAG." | tee -a ${LOG_FILE}
          else
            echo -e "PRE_TAG=${PRETAG}" | tee -a ${LOG_FILE}
          
            echo -e "\n\n" | tee -a ${LOG_FILE}
          
            echo -e "[CHANGE DIFF] (↓バージョン履歴ファイルの変更内容)" | tee -a ${LOG_FILE}
            git diff $PRETAG..${{ inputs.github-sha }} -- ${{ inputs.version-history-file }} | grep -E '^\+' | grep -v '+++' | sed -e 's/^\+//g' | tee -a ${LOG_FILE}
          
            echo -e "\n\n" | tee -a ${LOG_FILE}
          
            echo -e "[COMMIT LOG] (↓前回タグからの差分コミット内容)" | tee -a ${LOG_FILE}
            git log $PRETAG..${{ inputs.github-sha }} --oneline | tee -a ${LOG_FILE}
          fi
          
          echo ::set-output name=newtag::$NEWTAG

      - name:  Check Git diff and log PR Comments
        id: check-git-diff-and-log-comments
        run: |
          MESSAGE_FILE=pull_request_comment_message
          cat git_log | tee -a ${MESSAGE_FILE}
          gh pr comment -F ./${MESSAGE_FILE} "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          URL: ${{ inputs.github-pull-request-html-url }}
