name: create git tag
on:
  workflow_call:
    inputs:
      version-history-file:
        description: バージョン情報が記載されたファイルへのパス
        type: string
        required: true
      git-tag-suffix:
        description: git tagに付けるサフィックス
        type: string
        default: off
        required: false
    outputs:
      git-tag-version:
        description: "git tag version"
        value: ${{ jobs.create_git_tag.outputs.git-tag-version }}  

jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    outputs:
      git-tag-version: ${{ steps.version.outputs.tag }}
    steps:
      - name: clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: extract version
        id: version
        run: |
          newtag=$(grep -E "v[0-9]{1,}.[0-9]{1,}.[0-9]{1,}" ${{ inputs.version-history-file }} | sed -r 's/^.*(v[0-9]{1,}.[0-9]{1,}.[0-9]{1,}).*$/\1/' | sort -Vr | head -1)
          echo -e "NEW_TAG= ${newtag}"
          
          if [ "${{ inputs.git-tag-suffix }}" != "off" ]; then
            newtag="${newtag}-${{ inputs.git-tag-suffix }}"
          fi

          echo "tag=${newtag}" >> $GITHUB_OUTPUT

      - name:  create git tag
        id: git-tag
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}
