name: terraform destory
on:
  workflow_call:
    inputs:
      aws-region:
        description: AWSのリージョン名
        type: string
        default: ap-northeast-1
        required: false
      terraform-root-dir:
        description: Terraformコードが格納されているルートディレクトリ
        type: string
        required: true
      terraform-init-dir:
        description: terraform init を実行するディレクトリ
        type: string
        required: true
      terraform-init-option:
        description: terraform init のオプションを指定
        type: string
        default: off
        required: false
      terraform-workspace-name:
        description: terraform workspace名
        type: string
        default: default
        required: false
      terraform-destroy-option:
        description: terraform destroy のオプションを指定
        type: string
        default: off
        required: false
      terraform-version:
        description: terraformの実行バージョン
        type: string
        default: 1.1.9
        required: false
      git-checkout-ref:
        description: リポジトリをチェックアウトするときのブランチ、タグもしくはSHA
        type: string
        default: ""
        required: false
    secrets:
      aws-assume-role-arn:
        description: role to assume
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destory:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - if: ${{ inputs.git-checkout-ref != '' }} # <= ref が指定されていたら git checkout する
        name: git checkout
        id: checkout
        run: git checkout ${{ inputs.git-checkout-ref }}

      - name: setup terraform
        id: setup-terraform
        run: |
          : # デフォルトでインストールされているterraformを削除
          rm -f $(which terraform)
          
          : # setup terraform
          curl -sL https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/terraform_${{ inputs.terraform-version }}_linux_amd64.zip > /tmp/terraform.zip
          unzip /tmp/terraform.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/terraform
          which terraform
          terraform -v

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.aws-assume-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: terraform init
        id: init
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          if [ ${{ inputs.terraform-init-option }} = "off" ]; then
            terraform init
          else
            terraform init ${{ inputs.terraform-init-option }}
          fi

      - name: terraform workspace
        id: workspace
        working-directory: ${{ inputs.terraform-init-dir }}
        run: terraform workspace select ${{ inputs.terraform-workspace-name }} || terraform workspace new ${{ inputs.terraform-workspace-name }}

      - name: terraform destory
        id: destory
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          if [ ${{ inputs.terraform-destroy-option }} = "off" ]; then
            terraform destroy
          else
            terraform destroy ${{ inputs.terraform-destroy-option }}
          fi
