name: terraform ci with snyk
on:
  workflow_call:
    inputs:
      aws-region:
        description: AWSのリージョン名
        type: string
        default: ap-northeast-1
        required: false
      terraform-root-dir:
        description: Terraformコードが格納されているルートディレクトリ
        type: string
        required: true
      terraform-init-dir:
        description: terraform init を実行するディレクトリ
        type: string
        required: true
      terraform-init-option:
        description: terraform init のオプションを指定
        type: string
        default: off
        required: false
      terraform-workspace-name:
        description: terraform workspace名
        type: string
        default: default
        required: false
      terraform-plan-option:
        description: terraform plan のオプションを指定
        type: string
        default: off
        required: false
      terraform-show-option:
        description: terraform show のオプションを指定
        type: string
        default: off
        required: false
      terraform-version:
        description: terraformの実行バージョン
        type: string
        default: 1.1.9
        required: false
      tflint-version:
        description: tflintの実行バージョン
        type: string
        default: 0.36.3
        required: false
      tfcmt-version:
        description: tfcmtの実行バージョン
        type: string
        default: 3.2.2
        required: false
      reviewdog-version:
        description: reviewdogの実行バージョン
        type: string
        default: 0.14.1
        required: false
      git-checkout-ref:
        description: リポジトリをチェックアウトするときのブランチ、タグもしくはSHA
        type: string
        default: ""
        required: false
      github-pull-request-html-url:
        description:  GitHub Pull Request HTML URL
        type: string
        required: true
      snyk-iac-test-option:
        description: snyk iac test のオプションを指定
        type: string
        default: off
        required: false
    secrets:
      aws-assume-role-arn:
        description: role to assume
        required: true
      snyk-token:
        description: Snykトークン
        required: true
      github-token:
        description: GitHubトークン
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: clone repository
        id: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - if: ${{ inputs.git-checkout-ref != '' }} # <= ref が指定されていたら git checkout する
        name: git checkout
        id: checkout
        run: git checkout ${{ inputs.git-checkout-ref }}

      - name: setup terraform
        id: setup-terraform
        run: |
          : # デフォルトでインストールされているterraformを削除
          rm -f $(which terraform)
          
          : # setup terraform
          curl -sL https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/terraform_${{ inputs.terraform-version }}_linux_amd64.zip > /tmp/terraform.zip
          unzip /tmp/terraform.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/terraform
          which terraform
          terraform -v

      - name: setup reviewdog
        id: setup-reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v${{ inputs.reviewdog-version }}

      - name: reviewdog Version
        id: reviewdog-version
        run: reviewdog -version
        
      - name: setup tflint
        id: setup-tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v${{ inputs.tflint-version }}

      - name: tflint Version
        id: tflint-version
        run: tflint -v
        
      - name: setup tfcmt
        id: setup-tfcmt
        run: |
          wget https://github.com/suzuki-shunsuke/tfcmt/releases/download/v${{ inputs.tfcmt-version }}/tfcmt_linux_amd64.tar.gz
          tar -zxvf tfcmt_linux_amd64.tar.gz
          chmod +x ./tfcmt
          sudo mv -f ./tfcmt /usr/local/bin/tfcmt
          tfcmt -v

      - name: Snyk Setup
        id: setup-snyk
        uses: snyk/actions/setup@master

      - name: Snyk Version
        id: snyk-version
        run: snyk -v
        
      - name: configure aws credentials
        id: config-aws
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.aws-assume-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: terraform fmt
        id: tf-fmt
        run: terraform fmt -recursive -diff=true -check=true 2>&1 | tee -a terraform_fmt_result
        continue-on-error: true

      - name: Terraform fmt PR Comments
        id: tf-fmt-pr-comments
        run: |
          MESSAGE_FILE=pull_request_comment_message

          echo -e "[Terraform fmt]\n\n" | tee ${MESSAGE_FILE}

          cat terraform_fmt_result | tee -a ${MESSAGE_FILE}

          echo -e "\n\nTerraform fmt Finished." | tee -a ${MESSAGE_FILE}

          : # Terraform fmtのテスト結果がカラー表示されるため、そのままプルリクエストにコメントすると文字化けのようになる。
          : # sedでカラーを取り除く。
          sed -i -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" ${MESSAGE_FILE}
          
          gh pr comment -F ./${MESSAGE_FILE} "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          URL: ${{ inputs.github-pull-request-html-url }}

      - name: terraform init
        id: tf-init
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          if [ "${{ inputs.terraform-init-option }}" = "off" ]; then
            terraform init
          else
            terraform init ${{ inputs.terraform-init-option }}
          fi

      - name: terraform workspace
        id: workspace
        working-directory: ${{ inputs.terraform-root-dir }}
        run: terraform workspace select ${{ inputs.terraform-workspace-name }} || terraform workspace new ${{ inputs.terraform-workspace-name }}

      - name: terraform validate
        id: tf-validate
        run: |
          TERRAFORM_DIR=${{ inputs.terraform-root-dir }}
          TERRAFORM_VALIDATE_RESULT_FILE=terraform_validate_result

          : #pwdを参照する度に毎回結果が変わるので、別途スクリプト実行開始時点のディレクトリ位置を記録しておく。
          pwd=$(pwd)
          PWD=${pwd} 

          find ${TERRAFORM_DIR} -type d | grep -v "${TERRAFORM_DIR}/.terraform" | grep -v "module" | while read -r terraform_dirs
          do
            cd "${pwd}/${terraform_dirs}"
            echo "Checked Directory: ${pwd}/${terraform_dirs}"
            
            validate_result=$(terraform validate -no-color)
            echo -e "${validate_result}"
            
            cd ${PWD}
          done | tee -a ${TERRAFORM_VALIDATE_RESULT_FILE}
        continue-on-error: true

      - name: Terraform validate PR Comments
        id: tf-validate-pr-comments
        run: |
          MESSAGE_FILE=pull_request_comment_message

          echo -e "[Terraform Validate]\n\n" | tee ${MESSAGE_FILE}

          cat terraform_validate_result | tee -a ${MESSAGE_FILE}

          echo -e "\n\nTerraform validate Finished." | tee -a ${MESSAGE_FILE}
          
          gh pr comment -F ./${MESSAGE_FILE} "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          URL: ${{ inputs.github-pull-request-html-url }}

      - name: terraform lint with reviewdog
        id: tflint
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          tflint --format=checkstyle --module . \
          | reviewdog -f=checkstyle -name="tflint" -reporter="github-pr-review" -level="error" -fail-on-error="false" -filter-mode="nofilter"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github-token }}

      - name: terraform plan with tfcmt
        id: tf-plan-tfcmt
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          if [ "${{ inputs.terraform-plan-option }}" = "off" ]; then
            tfcmt plan -- terraform plan -no-color -out=tf.plan
          else
            tfcmt plan -- terraform plan ${{ inputs.terraform-plan-option }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: terraform show
        id: tf-show
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          if [ "${{ inputs.terraform-show-option }}" = "off" ]; then
            terraform show -json tf.plan > tf-plan.json
          else
            terraform show ${{ inputs.terraform-show-option }}
          fi

      - name: Snyk IaC Test
        id: snyk-iac-test
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          if [ "${{ inputs.snyk-iac-test-option }}" = "off" ]; then
            snyk iac test test tf-plan.json --scan=planned-values 2>&1 | tee -a snyk_test_result
          else
            snyk iac test ${{ inputs.snyk-iac-test-option }} 2>&1 | tee -a snyk_test_result
          fi
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        continue-on-error: true

      - name: Snyk IaC Test PR Comments
        id: snyk-iac-test-pr-comments
        working-directory: ${{ inputs.terraform-init-dir }}
        run: |
          MESSAGE_FILE_NAME=pull_request_comment_message
          echo -e "[Snyk IaC Test]\n\n" | tee ${MESSAGE_FILE_NAME}
          cat snyk_test_result >> ${MESSAGE_FILE_NAME}
          
          : # Snykのテスト結果がカラー表示されるため、そのままプルリクエストにコメントすると文字化けのようになる。
          : # sedでカラーを取り除く。
          sed -i -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" ${MESSAGE_FILE_NAME}
          gh pr comment -F ./${MESSAGE_FILE_NAME} "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          URL: ${{ inputs.github-pull-request-html-url }}
